//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.27 at 04:49:52 PM CEST 
//


package eu.trentorise.smartcampus.ac.provider.jaxbmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.trentorise.smartcampus.ac.provider.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Authorities_QNAME = new QName("", "authorities");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.trentorise.smartcampus.ac.provider.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Authorities }
     * 
     */
    public Authorities createAuthorities() {
        return new Authorities();
    }

    /**
     * Create an instance of {@link AuthorityMapping }
     * 
     */
    public AuthorityMapping createAuthorityMapping() {
        return new AuthorityMapping();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Authorities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authorities")
    public JAXBElement<Authorities> createAuthorities(Authorities value) {
        return new JAXBElement<Authorities>(_Authorities_QNAME, Authorities.class, null, value);
    }

}
